create table block (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   end_date DATE NOT NULL,
   start_date DATE NOT NULL,
   property_id BIGINT NOT NULL ,
   PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS block ADD CONSTRAINT FK_BLOCK_PROPERTY
    FOREIGN KEY (property_id) REFERENCES property;
